### ISSUE TITLE
请问mac系统的客户端应该选择哪个版本？

### ISSUE THREAD

**Issue by wwwxmu** [gwuhaolin/lightsocks#1]
我的服务端是ubuntu，客户端要在mac上用，要选择哪个版本？谢谢

**Comment by gwuhaolin** [comment]
> 我的服务端是ubuntu，客户端要在mac上用，要选择哪个版本？谢谢
服务端选 linux；
客户端选 darwin，darwin 是 Mac 内核版本代号。


386 是指 32 位操作系统
amd64 是指 64 位操作系统

**Comment by nanyang24** [comment]
NICE
