### ISSUE TITLE
包结构

### ISSUE THREAD

**Issue by XanthusL** [gwuhaolin/lightsocks#10]
目前的结构使导包语句中有`gwuhaolin/lightsocks`，没办法fork，只能go get后直接修改，这样就没办法提PR了

**Comment by gwuhaolin** [comment]
请参考以下方案：
- https://stackoverflow.com/questions/14323872/using-forked-package-import-in-go
- http://code.openark.org/blog/development/forking-golang-repositories-on-github-and-managing-the-import-path
