### ISSUE TITLE
存在内存泄露

### ISSUE THREAD

**Issue by gwuhaolin** [gwuhaolin/lightsocks#12]
现象：
- 使用期间内存占用只增加不见，启动时占用不到1M，运行一天后占用5M
- 内存增长速度很慢

初步通过 code review 无法找到导致内存泄露的原因，还请哪位大神帮忙看看，找出原因～

**Comment by gwuhaolin** [comment]
fixed in https://github.com/gwuhaolin/lightsocks/commit/dfe7c2d8a58fae1d2409abdca74f7c49337b3772

**Comment by gwuhaolin** [comment]
大致导致原因是 
`conn.SetDeadline(time.Now().Add(TIMEOUT))` 用法不当，应该在每次读写前更新超时时间戳。

**Comment by gwuhaolin** [comment]
> fixed in https://github.com/gwuhaolin/lightsocks/commit/dfe7c2d8a58fae1d2409abdca74f7c49337b3772


这个fix之后似乎还存在轻微的内存泄露，启动时占用不到1M，使用一天后停留在3M。

**Comment by Leviathan1995** [comment]
试试`pmap`看看内存的使用情况？

**Comment by rongyi** [comment]
http://mmcloughlin.com/posts/your-pprof-is-showing 可以看下这篇文章，可以再做个火焰图然后看下内存消耗在哪里，这样比较好debug

**Comment by gwuhaolin** [comment]
谢谢大家的建议，该问题已经解决。
