### ISSUE TITLE
server.go:44: accept tcp [::]:34612: accept4: too many open files

### ISSUE THREAD

**Issue by nickyfoto** [gwuhaolin/lightsocks#15]
server端一段时间后会出现 `server.go:44: accept tcp [::]:34612: accept4: too many open files`，是什么原因呢？

**Comment by gwuhaolin** [comment]
系统设置的最大文件打开数太小了，可以参考这篇文章修改 linux 系统配置：
https://support.xmatters.com/hc/en-us/articles/202089439--Too-many-open-files-error-on-Linux-Unix
