### ISSUE TITLE
后台运行自动失效

### ISSUE THREAD

**Issue by jaimecai** [gwuhaolin/lightsocks#16]
我用`nohup ./lightsocks-server &`启动之后，一段时间后连不上，需要重新启动启动才行，但是查看进程还在。怎样才能让它一直后台运行？

**Comment by gwuhaolin** [comment]
我用的 screen，nohup 是不会导致 lightsocks-server 连不上的。
你可以参考这里 https://unix.stackexchange.com/questions/4004/how-can-i-close-a-terminal-without-killing-the-command-running-in-it

**Comment by jaimecai** [comment]
我开着不关它一段时间后还是自动断了知道啥原因

**Comment by gwuhaolin** [comment]
有没有看到有日志输出，有的话贴下日志好分析原因。

**Comment by jaimecai** [comment]
```
server.go:44: accept tcp [::]:443: accept4: too many open files
server.go:44: accept tcp [::]:443: accept4: too many open files
server.go:44: accept tcp [::]:443: accept4: too many open files
server.go:44: accept tcp [::]:443:  @accept4: too many open files
server.go:44: accept tcp [::]:443: accept4: too many open files
server.go:44: accept tcp [::]:443: accept4: too many open files
```
运行一段时间后就出现了这个
@gwuhaolin

**Comment by gwuhaolin** [comment]
@jaimecai 你看这个和你相似的问题
https://github.com/gwuhaolin/lightsocks/issues/15

**Comment by jaimecai** [comment]
已解决 ulimit -n 99999
