### ISSUE TITLE
这里的混淆是什么原理？

### ISSUE THREAD

**Issue by kehao95** [gwuhaolin/lightsocks#2]
没有写清楚

**Comment by gwuhaolin** [comment]
感谢的话自己阅读写源码，实现原理非常简单。

**Comment by kk44** [comment]
@gwuhaolin 你好，请问源代码哪一部分是协议混淆呢？另外，源代码里只看到core里有基于256位的密码字节表做的简单映射就是“数据加密”吗？

**Comment by gwuhaolin** [comment]
@kk44 你说的对，就是这么简单。
混淆和解混淆的代码在 https://github.com/gwuhaolin/lightsocks/blob/master/core/cipher.go

**Comment by kk44** [comment]
它是对传输数据做简单的混淆（加密），不是协议混淆，是吧？
另外，如果出现密码中256个字节之外的数据会怎么样呢？

**Comment by gwuhaolin** [comment]
对传输数据在 byte 层面进行混淆（加密），后面我会写一篇文章详细介绍其原理，
以方便大家去实现 C 语言版的。
