### ISSUE TITLE
Windows 客户端无法启动

### ISSUE THREAD

**Issue by julianchan90** [gwuhaolin/lightsocks#22]
Windows 客户端双击之后，窗口只是闪了一下就消失了，请问这个要怎么处理呀？
谢谢！

**Comment by gwuhaolin** [comment]
因为第一次启动时的配置是不合法的，所以程序退出了。
其实是打印出了日志提示让你去 修改配置文件的。

要解决此问题你需要：
1. 修改配置文件 `.lightsocks.json`，加上正确的 `remote` 和 `password` 字段；
2. 重启 lightsocks-local
