### ISSUE TITLE
服务端和本地启动成功，但无法访问

### ISSUE THREAD

**Issue by Coande** [gwuhaolin/lightsocks#25]
服务端和本地启动成功，浏览器设置了7448代理，仍然无法访问，控制台不输出日志，什么情况？

**Comment by channel960608** [comment]
启动成功的话要用socks5的代理才行，可以用chrome的switchyomega的插件或者其他方法用代理

**Comment by gwuhaolin** [comment]
其配置和启动好 Lightsocks 后，本地的应用程序还不会通过 lightsocks-local 提供的 SOCKS5 代理服务进行网络连接，你还需要一些配置操作。由于我们常用 Chrome 浏览器，下面以 Chrome 为例讲解如果搭配 lightsocks 科学上网。

### 安装 (SwitchyOmega)[https://github.com/FelisCatus/SwitchyOmega]
第一步你需要安装 SwitchyOmega Chrome 插件，用于管理 Chrome 浏览器的网络代理。

### 配置 SwitchyOmega
1. 先配置一个 SOCKS5 代理
<img width="1048" alt="screen shot 2017-10-27 at 19 41 50" src="https://user-images.githubusercontent.com/5773264/32102856-b5fc1c72-bae3-11e7-94a7-b69aaf4c516f.png">
<img width="1127" alt="screen shot 2017-10-27 at 19 42 25" src="https://user-images.githubusercontent.com/5773264/32102858-b686127e-bae3-11e7-8da6-00be5b89c86a.png">

2.在配置一个自动切换
<img width="1032" alt="screen shot 2017-10-27 at 19 42 13" src="https://user-images.githubusercontent.com/5773264/32102857-b641c830-bae3-11e7-8fc6-c1d9220f3ef0.png">

<img width="1319" alt="screen shot 2017-10-27 at 19 42 47" src="https://user-images.githubusercontent.com/5773264/32102859-b6c1a582-bae3-11e7-9626-96d12d44bb7d.png">

`Rule List URL` 地址为 `https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt`。

3.使用自动切换
<img width="296" alt="screen shot 2017-10-27 at 19 57 02" src="https://user-images.githubusercontent.com/5773264/32102962-1c72bbbe-bae4-11e7-8410-44109876a038.png">

**Comment by TonyYuChufang** [comment]
@gwuhaolin 有没有办法让本地应用都走这个代理，不需要配置呢
