### ISSUE TITLE
代码lint问题

### ISSUE THREAD

**Issue by rongyi** [gwuhaolin/lightsocks#27]
代码注释写的挺不错的，但是我的编辑器打开还是有不少lint提示，比如：
1. if 条件里return 那么后面的else其实可以不要else这里block，直接写在下面github.com/gwuhaolin/lightsocks/server/server.go:143
2. fmt Error 错误写成Errorf的 github.com/gwuhaolin/lightsocks/cmd/config.go:36
3. 变量名Json ==> JSON等等

空了可以优化下

**Comment by rongyi** [comment]
对了，另外最好都对代码gofmt一下，这样比较规范一点

**Comment by gwuhaolin** [comment]
谢谢你的建议。

- 你用的什么编辑器写 GO，有什么优势；
- 哪套风格是最标准最科学的 GO 风格，求文档；

**Comment by rongyi** [comment]
Go为了避免风格争论，所以他只有一种最科学的Go风格，那就是用go自带的gofmt工具format过的代码，所以代码最好用gofmt过后提交代码库
我用的Emacs，可以看下我的emacs配置，当然主流编辑器都有相应的插件，你可以看下https://github.com/golang/lint 这个用作代码lint

**Comment by gwuhaolin** [comment]
谢谢你的建议，我会修改下代码风格。
