### ISSUE TITLE
加密

### ISSUE THREAD

**Issue by updater1234** [gwuhaolin/lightsocks#29]
问一下，这个默认有加密的吗？就是说默认有使用如chacha20这样的加密算法吗？

**Comment by gwuhaolin** [comment]
首先：混淆即加密，加密即混淆。

lightsocks 只专注于混淆，不关注加密，它使用非常简单的混淆算法，因此它更快更轻量级；

如果你对安全性有很高要，有两种选择：
1. 使用 lightsocks 的同时使用 HTTPS；
2. 使用其它使用了复杂加密算法的工具；
