### ISSUE TITLE
fail:dial tcp [ip]:[port]: getsockopt: connection timed out

### ISSUE THREAD

**Issue by ChenYouping** [gwuhaolin/lightsocks#3]
连接的时候出现这个错误, 请问是为什么?

**Comment by gwuhaolin** [comment]
看情况是无法连接到墙外的服务器，请检查端口和地址是否正确。

如果不行，请提供完整日志。

**Comment by felixliou** [comment]
您好，我也遇到了同样的问题，昨天安装后浏览器能正常的访问外网，但今天浏览器访问外网时出现等待较长时间后显示无法加载，终端上显示：
```bash
2017/10/12 14:07:45 dail remote [IP]:7448 fail:dial tcp [IP]:7448: getsockopt: connection timed out
```
而后重启服务器端程序仍不能解决，不知是什么原因

**Comment by gwuhaolin** [comment]
@felixliou 
你先确定你的 IP 有没有被封，IP 没有被封的话，就换端口试试。

**Comment by felixliou** [comment]
@gwuhaolin 更换端口后连接成功，谢谢！

**Comment by gwuhaolin** [comment]
服务器监听端口已经改为随机生成，去除GFW通过对端口判断进行拦截的能力。
