### ISSUE TITLE
superh cpu

### ISSUE THREAD

**Issue by delphinuz** [gwuhaolin/lightsocks#36]
您好，能否增加sh4( ST40-300)的binary，謝謝。

**Comment by gwuhaolin** [comment]
lightsocks 是通过 https://goreleaser.com 编译的，sh4( ST40-300) 的 goos 和 goarch 是什么？

**Comment by delphinuz** [comment]
GOOS=linux，GOARCH=sh4 不過看一下即使最新的go版本也還沒支援，只能等之後版本了。
