### ISSUE TITLE
能支持http代理吗？

### ISSUE THREAD

**Issue by wcw84** [gwuhaolin/lightsocks#38]
目前客户端似乎只有sock5，能支持http代理吗？
谢谢~

**Comment by gwuhaolin** [comment]
[可以使用 Polipo](http://xuhuan.leanote.com/post/Socks%E4%BB%A3%E7%90%86%E8%BD%AC%E6%8D%A2%E6%88%90HTTP%E4%BB%A3%E7%90%86)
