### ISSUE TITLE
智能模式还是全局模式？

### ISSUE THREAD

**Issue by honbolau** [gwuhaolin/lightsocks#4]
能都配置PAC或者白名单之类的？

**Comment by gwuhaolin** [comment]
PAC配置后期再支持，lightsocks 项目目前对标 https://github.com/shadowsocks/shadowsocks-libev

lightsocks 只是提供可翻墙的本地 SOCK5 代理，你需要提供 Chrome 代理 Proxy SwitchyOmega 去做智能转发。
