### ISSUE TITLE
如何预防MITM攻击？

### ISSUE THREAD

**Issue by kehao95** [gwuhaolin/lightsocks#5]

**Comment by henglinli** [comment]
你在搞事情啊?!不知道tls双向认证能行不？来个内行说说

**Comment by gwuhaolin** [comment]
个人认为预防中间人攻击的事情不是代理应该做的

- 中间人攻击是 HTTPS 要解决的事情
- 就算代理做了预防中间人攻击的事情也是无用的，因为在代理服务器到目标网站服务器直接如果是 HTTP 协议的话，黑客在这之间劫持的化，代理是无法干预的。

预防中间人攻击最好的方法就是 HTTPS，这也是为什么 Apple 强推它的原因。
