### ISSUE TITLE
配置文件路径问题

### ISSUE THREAD

**Issue by QQ2017** [gwuhaolin/lightsocks#66]
配置文件强制指定在 C:\Users\username\ 里面，这也太不灵活了吧，能不能支持下自定义路径，命令行传输的自定义路径并没有效果。

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by gwuhaolin** [comment]
和这个是一样的
https://github.com/gwuhaolin/lightsocks/issues/48
