### ISSUE TITLE
支持后台驻留

### ISSUE THREAD

**Issue by gwuhaolin** [gwuhaolin/lightsocks#9]

**Comment by TimothyYe** [comment]
后台驻留可以用其他方式实现：
systemd
upstart
supervisor
docker方式运行

感觉不需要程序自己支持了吧？

**Comment by gwuhaolin** [comment]
确实，这个优先级排到后面去

**Comment by mritd** [comment]
@gwuhaolin 已经提交了一个 Dockerfile，目前在 VPS 上运行良好 😂

refs #18

**Comment by gwuhaolin** [comment]
在服务器上[通过docker运行lightsocks-server](https://cloud.docker.com/u/gwuhaolin/repository/docker/gwuhaolin/lightsocks)，
在本机工作电脑通过 `nohup lightsocks-local &` 运行客户端。
